#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/tweetSaltC

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/tweetSaltC

OBJ_DEBUG = $(OBJDIR_DEBUG)/naclSupport.o $(OBJDIR_DEBUG)/tweetSaltC.o $(OBJDIR_DEBUG)/tweetnacl.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/naclSupport.o $(OBJDIR_RELEASE)/tweetSaltC.o $(OBJDIR_RELEASE)/tweetnacl.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/naclSupport.o: naclSupport.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c naclSupport.c -o $(OBJDIR_DEBUG)/naclSupport.o

$(OBJDIR_DEBUG)/tweetSaltC.o: tweetSaltC.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tweetSaltC.c -o $(OBJDIR_DEBUG)/tweetSaltC.o

$(OBJDIR_DEBUG)/tweetnacl.o: tweetnacl.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tweetnacl.c -o $(OBJDIR_DEBUG)/tweetnacl.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/naclSupport.o: naclSupport.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c naclSupport.c -o $(OBJDIR_RELEASE)/naclSupport.o

$(OBJDIR_RELEASE)/tweetSaltC.o: tweetSaltC.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tweetSaltC.c -o $(OBJDIR_RELEASE)/tweetSaltC.o

$(OBJDIR_RELEASE)/tweetnacl.o: tweetnacl.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tweetnacl.c -o $(OBJDIR_RELEASE)/tweetnacl.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

